import React from 'react'

const TextSection = () => {
  return (
    <div className='flex w-screen items-center justify-center my-[30px] md:my-[45px] lg:my-[60px]'>
      <div className='flex flex-col items-start justify-center w-[87.79%] md:w-[91.4%] lg:w-[76.8%] max-w-[1440px] text-start gap-4 lg:gap-8'>
       <h3 className='font-marcellus text-[28px] md:text-[32px] lg:text-[40px] text-lagoBlack2 w-full items-center text-center'>KVKK</h3>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>Bu bilgilendirme, 6698 sayılı “Kişisel Verilerin Korunması Kanunu” 10. maddesi gereğince ve yasal zorunluluk nedeniyle yapılmaktadır.</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>CEBECİ GLOBAL TURİZM TİCARET A.Ş. (Azura Deluxe Resort & Spa Hotel) olarak kişisel verilerinizin güvenliği hususuna azami hassasiyet göstermekteyiz. Bu bilinçle, şirket olarak ürün ve hizmetlerimizden faydalanan kişiler dahil, şirketimiz ile ilgili tüm şahıslara ait her türlü kişisel verilerin 6998 Sayılı Kişisel Verilerin Korunması Kanunu (KVKK)'na uygun olarak işlenerek muhafaza edilmesine büyük önem atfetmekteyiz. Bu sorumluluğumuz gereği KVKK'nın 3. maddesinde tanımlı şekli ile 'veri sorumlusu' sıfatı ile kişisel verilerinizi aşağıda izah edildiği surette ve mevzuat tarafından emredilen sınırlar çerçevesinde işlemekteyiz.</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>1- KİŞİSEL VERİLERİN İŞLENMESİ AMAÇLARI</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>Kişisel verileriniz (ad, soyad, doğum tarihi, kimlik ve pasaport bilgileri, iş, ev ve cep telefon numarası, e-posta adresi, cinsiyet, adres, meslek, eğitim, medeni durum, araç plakası, konaklama, kredi kartı, harcama ve uçuş bilgileri, alışveriş bilgileri, fatura bilgileri, tüketim tercihleri vb.) şirketimiz tarafından sunulan ürün ve hizmetlerden sizleri faydalandırmak için gerekli çalışmaların iş birimleri tarafından yapılması, ürün ve hizmetlerinin sunulabilmesi, aldığınız/alacağınız ürün ve hizmete ilişkin iletişim kurulabilmesi, ürün ve hizmetlerin sizlerin beğeni, kullanım alışkanlıkları ve ihtiyaçlarına göre özelleştirilerek sizlere önerilmesi, ürün/hizmet teklifi, (pazarlama faaliyetlerinde kullanılabilmesi), modelleme, raporlama, skorlama, şirketimiz insan kaynakları politikalarının yürütülmesi, şirketimiz ve şirketimizle ilişki içerisinde olan kişilerin hukuki ve ticari güvenliğinin temini, şirketimizin ticari ve iş stratejilerinin belirlenmesi ve uygulanması, şirketimiz ve iştiraklerimizin mevcut veya yeni ürün çalışmaları ve potansiyel müşteri tespiti vb amaçlar ile turizm, pazarlama, tanıtım ve reklam faaliyetleri ile ilişkili olarak ve yasal yükümlülükler nedeni ile KVKK'nın 5. ve 6. maddelerinde belirtilen kişisel veri işleme şartları ve amaçları dahilinde işlenmektedir.</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>2- KİŞİSEL VERİLERİN HANGİ AMAÇLA VE KİMLERE AKTARILACAĞI</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>Kişisel verileriniz şirketimiz tarafından sunulan ürün ve hizmetlerden sizleri faydalandırmak için gerekli çalışmaların iş birimlerimiz tarafından yapılması, ürün ve hizmetlerinin sunulabilmesi, aldığınız/alacağınız ürün ve hizmete ilişkin iletişim kurulabilmesi, ürün ve hizmetlerin sizlerin beğeni, kullanım alışkanlıkları ve ihtiyaçlarına göre özelleştirilerek sizlere önerilmesi, ürün/hizmet teklifi, (pazarlama faaliyetlerinde kullanılabilmesi), şirketimiz ve şirketimizle ilişki içerisinde olan kişilerin hukuki ve ticari güvenliğinin temini, şirketimizin ticari ve iş stratejilerinin belirlenmesi ve uygulanması amaçları ile iş ortaklarımıza, tedarikçilerimize, hissedarlarımıza, iştiraklarımıza, topluluk şirketlerimize, kanunen yetkili kamu kurumları, devlet güvenlik birimleri ve özel kişilere KVKK'nın 8. ve 9. maddelerinde belirtilen kişisel veri işleme şartları ve amaçları çerçevesinde aktarılabilecektir.</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>3- KİŞİSEL VERİ TOPLAMANIN YÖNTEMİ VE HUKUKİ SEBEBİ</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>Kişisel verileriniz her türlü sözlü, yazılı ya da elektronik ortamda, yukarıda yer verilen amaçlar doğrultusunda şirketimizce sunulan ürün ve hizmetlerin belirlenen yasal çerçevede sunulabilmesi ve bu kapsamda şirketimizin sözleşme ve yasadan doğan mesuliyetlerini eksiksiz ve doğru şekilde yerine getirebilmesi gayesiyle edinilir. Bu hukuki sebeple toplanan kişisel verileriniz KVKK'nın 5. ve 6. maddelerinde belirtilen kişisel veri işleme şartları ve amaçları kapsamında bu metnin 1. ve 2. maddelerinde belirtilen amaçlarla işlenebilmekte ve aktarılabilmektedir.</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>4-KİŞİSEL VERİ SAHİBİNİN HAKLARI</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>Kişisel veri sahibi olarak;</p>
       <ul className='marker:text-[8px] pl-4 list-disc text-lagoGray font-jost text-[12px] lg:text-[14px]'>
        <li>Kişisel verilerin işlenip işlenmediğini öğrenme,</li>
        <li>Kişisel verilerin işlenmişse buna ilişkin bilgi talep etme,</li>
        <li>Kişisel verileriniz işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme,</li>
        <li>Yurt içinde ve yurt dışında kişisel verilerin aktarıldığı 3. kişileri bilme,        </li>
        <li>Kişisel verilerin eksik ya da yanlış işlenmiş olması halinde bunların düzeltilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı 3. kişilere bildirilmesini isteme,</li>
        <li>KVKK ve ilgili kanun hükümlerine uygun olarak işlenmesine rağmen işlenmesini gerektiren sebeplerin ortadan kaldırılması halinde kişisel verilerin yok edilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı 3. kişilere bildirilmesini isteme,</li>
        <li>İşlenen verilerin münhasıran otomatik sistemler vasıtası ile analiz edilmesi suretiyle kişinin aleyhine bir sonucun ortaya çıkmasına itiraz etme,</li>
        <li>Kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarar uğraması halinde zararın giderilmesini talep etme haklarınız bulunmaktadır.</li>
       </ul>

       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>KVKK'nın 13. maddesinin 1. fıkrası gereğince yukarıda belirtilen haklarınızı kullanmak ile ilgili talebinizi 'yazılı' veya 'Kişisel verileri Koruma Kurulu'nun belirlediği diğer yöntemlerle şirketimize iletmeniz gerekmektedir. Kişisel Verileri Koruma Kurulu, şu aşamada herhangi bir yöntem belirlemediğinden başvurunuzu, KVKK gereğince yazılı olarak şirketimize iletmeniz gerekmektedir. Bu çerçevede şirketimize KVKK'nın 11. maddesi kapsamında yapacağınız başvurularda yazılı olarak başvurunuzu ilettiğiniz kanallar ve usuller aşağıda açıklanmaktadır.</p>
       <p className='text-[12px] lg:text-[14px] font-jost leading-normal text-lagoGray'>Yukarıda belirttiğiniz haklarınızı kullanmak için kimliğinizi tespit edici bilgiler ile KVKK'nın 11. maddesinde belirtilen haklardan kullanmayı talep ettiğiniz hakkınıza yönelik açıklamalarınızı içeren talebinizi; Başvuru Formunu doldurarak, formun imzalı bir nüshasını Azura Deluxe Resort & Spa Hotel, Avsallar Mah. İncekum Cad. No:76 Avsallar - Alanya - ANTALYA adresine kimliğinizi tespit edici belgeler ile bizzat elden iletebilir, Noter kanalı ile, iadeli taahhütlü mektupla veya KVKK'da belirtilen diğer yöntemlerle gönderebilirsiniz.</p>
       <span className='text-[12px] lg:text-[14px] font-bold font-jost text-lagoBlack'>CEBECİ GLOBAL TURİZM TİC. A.Ş. <br/>
       (Azura deluxe Resort & Spa Hotel)</span>
      </div>
    </div>
  )
}

export default TextSection
